### ISSUE TITLE
Benchmark logic changed, current one can't give negative results 

### ISSUE THREAD

**Issue by ivanfioravanti** [TristanBilot/mlx-benchmark#1]
@TristanBilot in commit ed51428 I see that logic for mps/mlx changed. I.e.: v[h] = (v["mps"] / v["mlx_gpu"] - 1) + 1
This code can't generate negative value but in the benchmark posted by you for M1 Pro they are visibile. 
It seems that last + 1 was not considered.

I will post a PR with Benchmark results for M3 Max using current code soon, but I think you need to tun again them on M1 Pro. 
No?

**Comment by TristanBilot** [comment]
Hi @ivanfioravanti!
Yes indeed this is an error, I'll remove it now! thanks :)

**Comment by TristanBilot** [comment]
I'll be just adding again few operations tonight and tomorrow will be good if you want to run the benchmark 😁

**Comment by ivanfioravanti** [comment]
Great @TristanBilot  
I've seen the commit for the fix. Benchmark added with PR #2 

Conv2d is really slow on MLX, strange.

**Comment by ivanfioravanti** [comment]
New PR created ready to go!
