### ISSUE TITLE
Minimum machine requirements for the benchmark

### ISSUE THREAD

**Issue by alexziskind1** [TristanBilot/mlx-benchmark#7]
Hi Tristan. I'm running this on a few machines, and the 8GB machines can't deal with it. Not that anyone will really try to use an 8GB machine for MLX, but wondering if you know of the minimum RAM requirements. My other machines are handling it just fine.

**Comment by TristanBilot** [comment]
Hi @alexziskind1 thanks for opening this issue. 

I'm not surprised that it doesn't work on 8GB Macs as the RAM can quickly grow up to 10GB on some benchmarks. 

Consequently, I'm not sure that we'll benchmark 8GB Macs, because we would have to create smaller benchmarks. Benchmarking on too easy examples would make the benchmarks not enough significant to compare operations on Mac or CUDA GPUs, which are extremely fast.

**Comment by alexziskind1** [comment]
makes perfect sense. Unfortunately, for the M3 variant, I only have the base model, so will have to skip that one. 

I'll sneak another question in here: if you already have others' results for machines like M1 pro and m3 max, do you want to stop at one, or do you want more results for those as well for averages?

**Comment by TristanBilot** [comment]
I think this could be valuable to keep track of duplicate benchmarks on the same chips. I'm sure results can be significantly different depending on what the user is doing on its Mac while running the bench (e.g. running other heavy processes that may impact the benchmark results).

We just have to think where to put these duplicate results: in the same files as existing benchs or in separate files, to avoid noisy results visualization.

**Comment by alexziskind1** [comment]
would it make sense to create a new file for each machine with some differentiator in the filename?

**Comment by TristanBilot** [comment]
Sorry for the very later answer!
For a better visualization and comparison of all results, I plan to write a script for plotting the results by parsing the benchmark files. With this new higher-level view, I'm pretty sure that almost no one will read the benchmark files directly. I don't think it's worth it to create separate files for each bench then.
I keep you in touch when I start working on this new viz feature.
